#!/bin/sh

usage(){
	echo "\n		usage: $0 <version-id>\n"
}

if [ $# -ne 1 ] ; then
	usage
	exit 1
fi

if ! sed 's/^\*   Version .*/\*   Version '$1'/g' README.md > .README.md.new ; then
	echo "Unable to change version." >&2
	exit 2
fi

mv .README.md.new README.md
git add README.md
git ci -m "Bump version to $1" README.md

